/**
 * Consistent Overhead Byte Stuffing, as used by the SPIKE Prime protocol.
 *
 * A direct port of LEGO's `cobs.py`, kept deliberately close to the original
 * so the two can be read side by side. `test/protocol.test.js` checks it
 * against vectors generated by that Python implementation.
 */

export const DELIMITER = 0x02;
const NO_DELIMITER = 0xff;
const COBS_CODE_OFFSET = DELIMITER;
const MAX_BLOCK_SIZE = 84;
const XOR = 3;

/** @param {Uint8Array} data @returns {Uint8Array} */
export function encode(data) {
  const buffer = [];
  let codeIndex = 0;
  let block = 0;

  const beginBlock = () => {
    codeIndex = buffer.length;
    buffer.push(NO_DELIMITER); // rewritten once the block is closed
    block = 1;
  };

  beginBlock();
  for (const byte of data) {
    if (byte > DELIMITER) {
      buffer.push(byte);
      block++;
    }
    if (byte <= DELIMITER || block > MAX_BLOCK_SIZE) {
      if (byte <= DELIMITER) {
        buffer[codeIndex] = byte * MAX_BLOCK_SIZE + block + COBS_CODE_OFFSET;
      }
      beginBlock();
    }
  }
  buffer[codeIndex] = block + COBS_CODE_OFFSET;

  return Uint8Array.from(buffer);
}

/** @param {Uint8Array} data @returns {Uint8Array} */
export function decode(data) {
  const buffer = [];

  const unescape = (code) => {
    if (code === 0xff) return [null, MAX_BLOCK_SIZE + 1];
    let value = Math.floor((code - COBS_CODE_OFFSET) / MAX_BLOCK_SIZE);
    let block = (code - COBS_CODE_OFFSET) % MAX_BLOCK_SIZE;
    if (block === 0) {
      block = MAX_BLOCK_SIZE;
      value -= 1;
    }
    return [value, block];
  };

  let [value, block] = unescape(data[0]);
  for (let i = 1; i < data.length; i++) {
    const byte = data[i];
    block--;
    if (block > 0) {
      buffer.push(byte);
      continue;
    }
    if (value !== null) buffer.push(value);
    [value, block] = unescape(byte);
  }

  return Uint8Array.from(buffer);
}

/**
 * Encode and frame a payload for transmission.
 * @param {Uint8Array} data @returns {Uint8Array}
 */
export function pack(data) {
  const encoded = encode(data);
  const frame = new Uint8Array(encoded.length + 1);
  // the XOR keeps a literal ctrl+C out of the stream
  for (let i = 0; i < encoded.length; i++) frame[i] = encoded[i] ^ XOR;
  frame[encoded.length] = DELIMITER;
  return frame;
}

/**
 * Unframe and decode a received frame.
 * @param {Uint8Array} frame @returns {Uint8Array}
 */
export function unpack(frame) {
  const start = frame[0] === 0x01 ? 1 : 0; // unused priority byte
  const body = frame.subarray(start, frame.length - 1);
  const unframed = new Uint8Array(body.length);
  for (let i = 0; i < body.length; i++) unframed[i] = body[i] ^ XOR;
  return decode(unframed);
}
