/**
 * Build the editor bundle, and optionally serve it.
 *
 *   node scripts/build.js            build once into dist/
 *   node scripts/build.js --serve    rebuild on change and serve on :8080
 *
 * Blockly ships its browser builds as UMD, which native ES modules cannot
 * import, so a bundling step is unavoidable. esbuild keeps it to one
 * dependency and well under a second.
 */

import { cp, mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import * as esbuild from 'esbuild';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outdir = join(root, 'dist');
const serve = process.argv.includes('--serve');

await rm(outdir, { recursive: true, force: true });
await mkdir(outdir, { recursive: true });

/**
 * Bundle the simulator's Python into a module the worker can unpack.
 *
 * Generated from the simulator package rather than kept as a copy, so the
 * Python running in the browser is the same Python the simulator tests run
 * against. A copy would drift, and a robot that behaved differently in the
 * browser is the one outcome this project cannot afford.
 */
/**
 * The mat menu, generated from the mats themselves.
 *
 * The editor needs the list before the simulator has loaded — a student picks
 * a mat and *then* connects — so it cannot ask the worker. Generating it from
 * the same JSON files the simulator reads keeps one source of truth: a mat
 * that exists is offered, and a mat that is offered exists.
 */
async function bundleMatCatalogue() {
  const directory = join(root, '..', 'spike-sim', 'spike_sim', 'mats');
  const entries = [];

  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (!entry.name.endsWith('.json')) continue;
    const mat = JSON.parse(await readFile(join(directory, entry.name), 'utf8'));
    entries.push({
      name: entry.name.replace(/\.json$/, ''),
      title: mat.title ?? entry.name,
      teaches: mat.teaches ?? '',
      order: mat.order ?? 99,
    });
  }

  entries.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));

  const generated = join(root, 'src', 'generated');
  await mkdir(generated, { recursive: true });
  await writeFile(
    join(generated, 'mat-catalogue.js'),
    `// Generated by scripts/build.js from spike-sim/spike_sim/mats. Do not edit.\n`
      + `export const MATS = ${JSON.stringify(entries, null, 2)};\n`,
    'utf8',
  );
  return entries.length;
}

/** The robot menu, generated from the builds themselves. See bundleMatCatalogue. */
async function bundleRobotCatalogue() {
  const directory = join(root, '..', 'spike-sim', 'spike_sim', 'robots');
  const entries = [];

  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (!entry.name.endsWith('.json')) continue;
    const robot = JSON.parse(await readFile(join(directory, entry.name), 'utf8'));
    entries.push({
      name: entry.name.replace(/\.json$/, ''),
      title: robot.title ?? entry.name,
      teaches: robot.teaches ?? '',
      wheelDiameterMm: robot.wheelDiameterMm,
      axleTrackMm: robot.axleTrackMm,
      order: robot.order ?? 99,
    });
  }

  entries.sort((a, b) => a.order - b.order || a.name.localeCompare(b.name));

  const generated = join(root, 'src', 'generated');
  await mkdir(generated, { recursive: true });
  await writeFile(
    join(generated, 'robot-catalogue.js'),
    `// Generated by scripts/build.js from spike-sim/spike_sim/robots. Do not edit.\n`
      + `export const ROBOTS = ${JSON.stringify(entries, null, 2)};\n`,
    'utf8',
  );
  return entries.length;
}

async function bundleSimulatorSources() {
  const packageRoot = join(root, '..', 'spike-sim', 'spike_sim');
  const files = {};

  async function walk(directory, prefix) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (entry.name === '__pycache__') continue;
      const full = join(directory, entry.name);
      const key = prefix ? `${prefix}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        await walk(full, key);
      } else if (entry.name.endsWith('.py') || entry.name.endsWith('.json')) {
        // .json as well as .py: the mat catalogue is data, and a student in
        // the browser needs the same mats as one at a command line.
        files[key] = await readFile(full, 'utf8');
      }
    }
  }
  await walk(packageRoot, '');

  const generated = join(root, 'src', 'generated');
  await mkdir(generated, { recursive: true });
  await writeFile(
    join(generated, 'simulator-sources.js'),
    '// Generated by scripts/build.js from spike-sim/spike_sim. Do not edit.\n' +
      `// ${Object.keys(files).length} files, ` +
      `${Math.round(Object.values(files).join('').length / 1024)} KB of Python.\n` +
      `export const simulatorSources = ${JSON.stringify(files, null, 1)};\n`,
    'utf8',
  );
  console.log(`Bundled ${Object.keys(files).length} simulator source files`);
}

await bundleMatCatalogue();
await bundleRobotCatalogue();
await bundleSimulatorSources();

// After the catalogues, because an example records the robot it was written
// for and reads it from the one just written. Imported here rather than at the
// top for the same reason: it reaches for a generated module.
const { buildExamples } = await import('./gen-examples.mjs');
await buildExamples();

// Everything above is what `src/generated/` holds, and it is all that the
// tests need. The bundle below is not, so `npm test` asks for this much and
// stops, and a test run still needs no build.
if (process.argv.includes('--generate-only')) process.exit(0);

// Blockly's icons, sounds and cursors. The workspace is injected with
// media: 'media/', so they have to sit beside index.html.
await cp(join(root, 'node_modules/blockly/media'), join(root, 'media'), {
  recursive: true,
});

const options = {
  entryPoints: {
    app: join(root, 'src/app.js'),
    viewer: join(root, 'src/viewer/main.js'),
    // The in-browser simulator. Its own entry point because a worker is
    // loaded by URL, not imported.
    'simulator-worker': join(root, 'src/simulator-worker.js'),
  },
  outdir,
  bundle: true,
  format: 'esm',
  // three.js and the LDraw loader are reached only through a dynamic import,
  // so splitting keeps them out of the editor's initial download
  splitting: true,
  target: ['chrome111', 'edge111', 'firefox115', 'safari16'],
  // Source maps while developing; not in a production build, where they
  // would be several megabytes of a deployment nobody debugs from.
  sourcemap: serve,
  // Blockly is most of the bundle; minifying takes it from ~1.2MB to ~600KB,
  // which matters on a school connection. Skipped while serving so that stack
  // traces stay readable during development.
  minify: !serve,
  logLevel: 'info',
};

if (serve) {
  const context = await esbuild.context(options);
  await context.watch();
  const { host, port } = await context.serve({ servedir: root, port: 8080 });
  console.log(`\nEditor running at http://${host === '0.0.0.0' ? 'localhost' : host}:${port}`);
  console.log('Start the simulator in another terminal:');
  console.log('  cd ../spike-sim && python3 -m spike_sim\n');
} else {
  await esbuild.build(options);
  console.log('Built dist/app.js and dist/viewer.js');
}
