#!/usr/bin/env python3
"""
Emit conformance vectors for the JavaScript protocol layer.

The vectors are produced by LEGO's own vendored codec, so the browser client
is checked against the same source of truth the simulator is. Regenerate with:

    python3 scripts/gen-vectors.py > test/vectors.json
"""
import json
import os
import sys

sys.path.insert(
    0, os.path.join(os.path.dirname(__file__), "..", "..", "spike-sim")
)

from spike_sim import wire  # noqa: E402
from spike_sim.vendor import cobs  # noqa: E402
from spike_sim.vendor import messages as lego  # noqa: E402
from spike_sim.vendor.crc import crc  # noqa: E402

HELLO = (
    'import runloop\nfrom hub import light_matrix\n'
    'async def main():\n    await light_matrix.write("Hi")\n'
    'runloop.run(main())\n'
).encode("utf8")

COBS_CASES = [
    b"",
    b"\x00",
    b"\x01\x02\x03",
    b"\x02" * 10,
    b"\x00" * 100,
    bytes(range(256)),
    bytes(range(256)) * 2,      # forces multiple maximum-size blocks
    HELLO,
]

CRC_CASES = [
    (b"", 0),
    (b"a", 0),
    (b"abc", 0),
    (b"abcd", 0),               # already 4-aligned, no padding
    (b"abcde", 0),              # padded to 8
    (HELLO, 0),
    (HELLO, 0x12345678),        # non-zero seed, as used for running CRCs
]

REQUESTS = [
    ("InfoRequest", lego.InfoRequest()),
    ("ClearSlotRequest", lego.ClearSlotRequest(3)),
    ("StartFileUploadRequest", lego.StartFileUploadRequest("program.py", 0, crc(HELLO))),
    ("TransferChunkRequest", lego.TransferChunkRequest(crc(HELLO), HELLO)),
    ("ProgramFlowRequestStart", lego.ProgramFlowRequest(False, 0)),
    ("ProgramFlowRequestStop", lego.ProgramFlowRequest(True, 0)),
    ("DeviceNotificationRequest", lego.DeviceNotificationRequest(100)),
]


# Hub -> client, built by the simulator's hub-side codec. The browser client
# must decode every one of these.
RESPONSES = [
    ("InfoResponse", wire.info_response(
        rpc_major=3, rpc_minor=1, rpc_build=2,
        firmware_major=4, firmware_minor=5, firmware_build=6,
        max_packet_size=244, max_message_size=1024, max_chunk_size=512,
    )),
    ("StartFileUploadResponseOk", wire.status_response(0x0D, True)),
    ("TransferChunkResponseFail", wire.status_response(0x11, False)),
    ("ProgramFlowResponseOk", wire.status_response(0x1F, True)),
    ("ClearSlotResponseFail", wire.status_response(0x47, False)),
    ("ProgramFlowNotificationStart", wire.program_flow_notification(False)),
    ("ProgramFlowNotificationStop", wire.program_flow_notification(True)),
    ("ConsoleNotification", wire.console_notification("Hello, world!\n")),
    ("ConsoleNotificationUnicode", wire.console_notification("caf\u00e9 \u2014 25\u00b0\n")),
    ("DeviceNotification", wire.device_notification([
        wire.battery_entry(87),
        wire.imu_entry(1, 2, 900, -150, 30, (0, 0, 1000), (1, -2, 3)),
        wire.matrix_5x5_entry(list(range(0, 100, 4))),
        wire.motor_entry(port=0, device_type=49, absolute_position=-90,
                         power=75, speed=50, position=1234),
        wire.motor_entry(port=1, device_type=49, absolute_position=90,
                         power=-75, speed=-50, position=-4321),
        wire.color_entry(port=2, color=9, rgb=(200, 30, 30)),
        wire.distance_entry(port=3, distance_mm=451),
        wire.force_entry(port=4, value=33, pressed=True),
        wire.matrix_3x3_entry(port=5, pixels=[1, 2, 3, 4, 5, 6, 7, 8, 9]),
    ])),
    ("DeviceNotificationNothingInRange", wire.device_notification([
        wire.distance_entry(port=3, distance_mm=-1),
        wire.color_entry(port=2, color=-1, rgb=(0, 0, 0)),
    ])),
]


def hexed(data: bytes) -> str:
    return data.hex()


vectors = {
    "note": "Generated by scripts/gen-vectors.py from LEGO's vendored codec. Do not hand-edit.",
    "cobs": [
        {"payload": hexed(case), "framed": hexed(cobs.pack(case))}
        for case in COBS_CASES
    ],
    "crc": [
        {"data": hexed(data), "seed": seed, "expected": crc(data, seed)}
        for data, seed in CRC_CASES
    ],
    "requests": [
        {"name": name, "serialized": hexed(message.serialize())}
        for name, message in REQUESTS
    ],
    "responses": [
        {"name": name, "payload": hexed(payload)} for name, payload in RESPONSES
    ],
}

print(json.dumps(vectors, indent=2))
